export const HISTORICAL_REGION = {
  WESTERN_EUROPE: "westernEurope",
  CENTRAL_EUROPE: "centralEurope",
  EASTERN_EUROPE: "easternEurope",
  NORTHERN_EUROPE: "northernEurope",
  SOUTHERN_EUROPE: "southernEurope",
  IBERIA: "iberia",
  ITALIAN_STATES: "italianStates",
  HOLY_ROMAN_EMPIRE: "holyRomanEmpire",
  FRANCE: "france",
  ENGLAND: "england",
  SCANDINAVIA: "scandinavia",
  POLAND_LITHUANIA: "polandLithuania",
  BALKANS: "balkans",
  BYZANTINE_SPHERE: "byzantineSphere",
} as const;

export type HistoricalRegion =
  (typeof HISTORICAL_REGION)[keyof typeof HISTORICAL_REGION];

export const HISTORICAL_REGION_LABEL: Record<HistoricalRegion, string> = {
  [HISTORICAL_REGION.WESTERN_EUROPE]: "Europa occidental",
  [HISTORICAL_REGION.CENTRAL_EUROPE]: "Europa central",
  [HISTORICAL_REGION.EASTERN_EUROPE]: "Europa oriental",
  [HISTORICAL_REGION.NORTHERN_EUROPE]: "Europa norteña",
  [HISTORICAL_REGION.SOUTHERN_EUROPE]: "Europa meridional",
  [HISTORICAL_REGION.IBERIA]: "Iberia",
  [HISTORICAL_REGION.ITALIAN_STATES]: "Estados italianos",
  [HISTORICAL_REGION.HOLY_ROMAN_EMPIRE]: "Sacro Imperio Romano Germánico",
  [HISTORICAL_REGION.FRANCE]: "Francia",
  [HISTORICAL_REGION.ENGLAND]: "Inglaterra",
  [HISTORICAL_REGION.SCANDINAVIA]: "Escandinavia",
  [HISTORICAL_REGION.POLAND_LITHUANIA]: "Polonia-Lituania",
  [HISTORICAL_REGION.BALKANS]: "Balcanes",
  [HISTORICAL_REGION.BYZANTINE_SPHERE]: "Esfera bizantina",
};

const REGION_COMPATIBILITY: Record<HistoricalRegion, HistoricalRegion[]> = {
  [HISTORICAL_REGION.WESTERN_EUROPE]: [
    HISTORICAL_REGION.FRANCE,
    HISTORICAL_REGION.ENGLAND,
    HISTORICAL_REGION.IBERIA,
    HISTORICAL_REGION.HOLY_ROMAN_EMPIRE,
  ],
  [HISTORICAL_REGION.CENTRAL_EUROPE]: [
    HISTORICAL_REGION.HOLY_ROMAN_EMPIRE,
    HISTORICAL_REGION.POLAND_LITHUANIA,
    HISTORICAL_REGION.ITALIAN_STATES,
  ],
  [HISTORICAL_REGION.EASTERN_EUROPE]: [
    HISTORICAL_REGION.POLAND_LITHUANIA,
    HISTORICAL_REGION.BALKANS,
    HISTORICAL_REGION.BYZANTINE_SPHERE,
  ],
  [HISTORICAL_REGION.NORTHERN_EUROPE]: [
    HISTORICAL_REGION.SCANDINAVIA,
    HISTORICAL_REGION.ENGLAND,
  ],
  [HISTORICAL_REGION.SOUTHERN_EUROPE]: [
    HISTORICAL_REGION.ITALIAN_STATES,
    HISTORICAL_REGION.IBERIA,
    HISTORICAL_REGION.BALKANS,
    HISTORICAL_REGION.BYZANTINE_SPHERE,
  ],
  [HISTORICAL_REGION.IBERIA]: [
    HISTORICAL_REGION.WESTERN_EUROPE,
    HISTORICAL_REGION.SOUTHERN_EUROPE,
  ],
  [HISTORICAL_REGION.ITALIAN_STATES]: [
    HISTORICAL_REGION.SOUTHERN_EUROPE,
    HISTORICAL_REGION.CENTRAL_EUROPE,
    HISTORICAL_REGION.HOLY_ROMAN_EMPIRE,
  ],
  [HISTORICAL_REGION.HOLY_ROMAN_EMPIRE]: [
    HISTORICAL_REGION.CENTRAL_EUROPE,
    HISTORICAL_REGION.WESTERN_EUROPE,
    HISTORICAL_REGION.ITALIAN_STATES,
  ],
  [HISTORICAL_REGION.FRANCE]: [HISTORICAL_REGION.WESTERN_EUROPE],
  [HISTORICAL_REGION.ENGLAND]: [
    HISTORICAL_REGION.WESTERN_EUROPE,
    HISTORICAL_REGION.NORTHERN_EUROPE,
  ],
  [HISTORICAL_REGION.SCANDINAVIA]: [HISTORICAL_REGION.NORTHERN_EUROPE],
  [HISTORICAL_REGION.POLAND_LITHUANIA]: [
    HISTORICAL_REGION.EASTERN_EUROPE,
    HISTORICAL_REGION.CENTRAL_EUROPE,
  ],
  [HISTORICAL_REGION.BALKANS]: [
    HISTORICAL_REGION.EASTERN_EUROPE,
    HISTORICAL_REGION.SOUTHERN_EUROPE,
    HISTORICAL_REGION.BYZANTINE_SPHERE,
  ],
  [HISTORICAL_REGION.BYZANTINE_SPHERE]: [
    HISTORICAL_REGION.EASTERN_EUROPE,
    HISTORICAL_REGION.SOUTHERN_EUROPE,
    HISTORICAL_REGION.BALKANS,
  ],
};

export function areHistoricalRegionsCompatible(
  aRegions: HistoricalRegion[] | undefined,
  bRegions: HistoricalRegion[] | undefined,
): boolean {
  if (!aRegions?.length || !bRegions?.length) {
    return true;
  }

  return aRegions.some((aRegion) =>
    bRegions.some(
      (bRegion) =>
        aRegion === bRegion ||
        REGION_COMPATIBILITY[aRegion].includes(bRegion) ||
        REGION_COMPATIBILITY[bRegion].includes(aRegion),
    ),
  );
}
